[package]
name = "hashlife-wasm"
version = "0.1.0"
authors = ["amlo <xplzjwz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.69"
algo = { path = "../algo" }
js-sys = "0.3.46"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false